/** Every user-facing string on the deploy and build pages (plans/feat-deploy.md). OpenRuntime is the platform. */
import type { BuildStatus } from './types'

export const copy = {
  deploy: {
    title: 'Deploy an agent',
    description: 'Upload your code and OpenRuntime builds and starts it.',
    drop: "Drop your agent's .zip here, or",
    choose: 'Choose file',
    limit: 'up to 100 MB',
    fileLabel: 'Agent package (.zip)',
    removeFile: 'Remove file',
    zipOnly: 'Choose a .zip file.',
    chooseFirst: 'Choose a .zip first.',
    checking: 'Checking the zip…',
    name: 'Name',
    namePlaceholder: 'my-agent',
    nameHint: 'Lowercase letters, digits, dots, dashes and underscores work best.',
    version: 'Version',
    versionHint: 'x.y.z. Leave empty to use the version in the zip.',
    versionNeeded: 'Set a version (x.y.z): the zip has none.',
    versionFormat: 'Use x.y.z, like 1.2.0.',
    current: (v: string, next: string) => `Current version ${v}, next suggested ${next}`,
    use: (v: string) => `Use ${v}`,
    advanced: 'Advanced: ports, environment, storage',
    ports: 'Ports',
    portsHint: 'Comma-separated container ports (default 8000).',
    portsFormat: 'Use port numbers separated by commas, like 8000,9000.',
    env: 'Environment variables',
    envKey: 'Name',
    envValue: 'Value',
    addEnv: 'Add variable',
    removeEnv: (k: string) => `Remove ${k || 'variable'}`,
    storage: 'Persistent storage',
    storagePath: 'Storage path',
    storagePathHint: 'Where the volume mounts, like /workspace.',
    inbound: 'Inbound format',
    inboundDefault: 'Server default',
    submit: (name: string) => (name ? `Deploy ${name}` : 'Deploy'),
    uploading: (done: string, total: string) => `Uploading ${done} of ${total}`,
    cancel: 'Cancel upload',
    cancelled: 'Upload cancelled.',
    fixFirst: 'Fix the items marked ✕ first: the server would reject this zip.',
    failed: "Couldn't deploy",
    needs: 'What your zip needs',
    needsCompact: 'Your zip needs: Dockerfile · entrypoint · version · ≤ 100 MB',
    advisory: "This zip couldn't be read here; OpenRuntime checks it when you deploy.",
    items: {
      dockerfile: 'Dockerfile in the root, with a FROM line',
      entrypoint: 'A Python entrypoint: main.py or __main__.py, at the root or in src/',
      version: 'A version (x.y.z) in AgentCard.json or pyproject.toml, or set below',
      size: 'Under 100 MB, 1,000 files and 200 MB unzipped',
    },
    itemState: { pass: 'passed', fail: 'failed', unknown: 'not checked yet' },
    terminal: 'Prefer the terminal?',
    terminalHint: 'Run this command to upload from your machine.',
    copyCommand: 'Copy command',
  },
  methods: {
    label: 'How to deploy',
    upload: 'Upload a zip',
    github: 'From GitHub',
    registry: 'From a registry',
  },
  github: {
    notConfigured: 'GitHub isn’t set up on this OpenRuntime server.',
    notConfiguredHint:
      'An admin needs to add a GitHub OAuth app (GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET). Until then, upload a zip.',
    useUpload: 'Use Upload instead',
    connectedAs: (login: string) => `Connected as ${login}`,
    switchAccount: 'Switch account',
    connect: 'Connect GitHub',
    reconnect: 'Reconnect GitHub',
    connectHint: 'OpenRuntime needs access to your repositories, public ones too.',
    invalid: 'Your GitHub connection expired.',
    waiting: 'Finish connecting in the GitHub window…',
    connectFailed: "Couldn't start connecting to GitHub. Try again.",
    blocked: 'Your browser blocked the GitHub window. Allow pop-ups for this site, or',
    openHere: 'open it here',
    what: 'your repositories',
    search: 'Search repositories',
    searchPlaceholder: 'Repository name or description',
    reposLabel: 'Repository',
    loading: 'Loading GitHub',
    loadingRepos: 'Loading repositories',
    noRepos: (login: string) => `No repositories on ${login}`,
    noReposHint: 'Push an agent repository to this GitHub account, or upload a zip instead.',
    noMatch: (q: string) => `No repositories match “${q}”`,
    noMatchHint: 'Search by owner or repository name.',
    clearSearch: 'Clear search',
    private: 'Private',
    public: 'Public',
    updated: (ago: string) => `updated ${ago}`,
    branch: 'Branch',
    branchHint: (def: string) => `The repository’s default is ${def}.`,
    branchRequired: 'Enter a branch to build from.',
    pickFirst: 'Pick a repository first.',
    submit: (repo: string) => (repo ? `Deploy ${repo}` : 'Deploy'),
    needs: 'What your repo needs',
    needsNote: 'OpenRuntime checks these after cloning.',
    shown: (n: number) => `Showing your ${n} most recently updated repositories.`,
  },
  registry: {
    reference: 'Image reference',
    placeholder: 'registry.nasiko.dev/acme/support-bot:1.2.0',
    hint: (host: string) => `host/owner/name:tag. Allowed hosts: ${host} and any your admin added.`,
    format: 'Use host/owner/name:tag, like registry.nasiko.dev/acme/support-bot:1.2.0.',
    submit: 'Import and deploy',
    importing: 'Importing (pull or build, then deploy)',
    usual: 'usually 1–5 min',
    keepUsing: 'You can keep using OpenRuntime; closing the tab stops watching.',
    disabled: 'Registry import is turned off on this OpenRuntime server.',
    disabledHint: 'An admin can turn it on. Until then, upload a zip or deploy from GitHub.',
    needs: 'What the image needs',
    items: [
      'An OpenRuntime agent package, or a runnable image',
      'From an allowed host',
      'Public over HTTPS: registry logins aren’t supported',
    ],
    notRunning: 'Imported, but the agent did not start.',
    openAgent: 'Open agent',
  },
  /** Background follow (§5, design review 8): one toast when a build finishes away from its page. */
  toast: {
    failed: (name: string) => `${name} failed`,
    seeWhy: 'See why',
    notRunning: (name: string) => `${name} was imported, but did not start`,
    // The sidebar's Agents item (Builds is its sub-page): what a screen reader hears after "Agents".
    agentsBadge: (n: number) => `${n} build${n === 1 ? '' : 's'} in progress`,
  },
  /** §7 entry points. */
  entry: {
    label: 'Deploy an agent',
    orCli: 'Or use the CLI:',
  },
  agentBuilds: {
    what: 'builds',
    empty: 'No builds from OpenRuntime yet',
    emptyHint: 'Deployed with `nasiko deploy`? That path pushes an image without a build here.',
    deploy: 'Deploy a new version',
    label: 'Builds of this agent',
    last20: 'The last 20 builds.',
  },
  builds: {
    title: 'Builds',
    description: 'Every build of the agents you can see. In-progress builds stay on top.',
    what: 'builds',
    empty: 'No builds yet',
    emptyHint: 'Deploy an agent and its build shows up here.',
    loading: 'Loading builds',
    noMatch: 'No builds match these filters',
    noMatchHint: 'Try another status or search, or clear the filters.',
    clearFilters: 'Clear filters',
    searchLabel: 'Search builds',
    searchPlaceholder: 'Agent name or version',
    filterLabel: 'Status',
    newerServer: 'Builds need a newer OpenRuntime server.',
    noRights: "You don't have deploy rights on this server.",
    next: 'Next page',
    previous: 'Previous page',
    unknownAgent: 'Deleted agent',
    colBuild: 'Build',
    colStatus: 'Status',
    colSource: 'Source',
    colStarted: 'Started',
    colDuration: 'Duration',
  },
  filter: { all: 'All', active: 'In progress', failed: 'Failed', success: 'Succeeded' },
  status: {
    queued: 'Queued',
    building: 'Building',
    success: 'Succeeded',
    failed: 'Failed',
    notRunning: 'Not running',
    running: 'Running',
  } satisfies Record<BuildStatus | 'notRunning' | 'running', string>,
  source: {
    github: (repo: string, commit: string | null) =>
      commit ? `${repo}@${commit.slice(0, 7)}` : repo,
    upload: 'Zip upload',
  },
  build: {
    what: 'this build',
    loading: 'Loading build',
    notFound: 'Build not found',
    notFoundHint: "It may belong to an agent you can't see, or its agent was deleted.",
    allBuilds: 'All builds',
    breadcrumb: 'Builds',
    started: (ago: string) => `started ${ago}`,
    finishedIn: (d: string) => `finished in ${d}`,
    uploaded: (file: string) => `Uploaded ${file}`,
    leave: 'You can leave this page — the build keeps going.',
    details: 'Details',
    source: 'Source',
    version: 'Version',
    agent: 'Agent',
    logs: 'Build logs',
    logsUnavailable: 'need a newer OpenRuntime server',
    stepsLabel: 'Build progress',
    running: (name: string) => `${name} is running`,
    notRunning: 'Built, but not running',
    notRunningHint: 'The image built, but the agent did not start. Open the agent to see why.',
    chat: 'Chat with it',
    openAgent: 'Open agent',
    deployAgain: 'Deploy again',
    deployAs: (v: string) => `Deploy as v${v}`,
    failedTitle: 'Build failed',
    slow: (timeout: string) => `Taking longer than usual · builds time out after ${timeout}`,
    usual: 'usually 1–3 min',
    inProgress: 'in progress',
    stepOf: (n: number, total: number) => `step ${n} of ${total}`,
    pending: 'pending',
    done: 'done',
  },
  steps: {
    queued: 'Queued',
    building: 'Building image',
    deploying: 'Deploying',
    running: 'Running',
  },
  errors: {
    generic: { problem: 'The build failed.', fix: 'Check the agent package, then deploy again.' },
    githubDisconnected: {
      problem: 'GitHub is not connected.',
      fix: 'Connect GitHub on the Deploy page, then deploy again.',
    },
    cloneFailed: {
      problem: 'The repository could not be cloned.',
      fix: 'Check the repository and branch, then deploy again.',
    },
    noVersion: {
      problem: 'No version was found.',
      fix: 'Set a version (x.y.z) on the Deploy page or in AgentCard.json or pyproject.toml.',
    },
    versionConflict: (v: string) => ({
      problem: `Version ${v} already exists.`,
      fix: 'Versions are immutable: deploy it under the next version.',
    }),
    noDockerfile: {
      problem: 'No Dockerfile in the zip.',
      fix: 'Add a Dockerfile at the root of the zip.',
    },
    noFrom: {
      problem: 'The Dockerfile has no FROM line.',
      fix: 'Start the Dockerfile with a FROM instruction.',
    },
    noEntrypoint: {
      problem: 'No Python entrypoint.',
      fix: 'Add main.py, src/main.py, __main__.py or src/__main__.py.',
    },
    tooLarge: {
      problem: 'The zip is over 100 MB.',
      fix: 'Remove large files (data, virtualenvs) and zip again.',
    },
    tooBig: {
      problem: 'The zip has too many files or unzips too large.',
      fix: 'Leave out dependencies and build output (node_modules, .venv, dist), then zip again: at most 1,000 entries and 200 MB unzipped.',
    },
  },
} as const
