/**
 * Every user-facing string of the LLM router page (plan §4). UI copy never cites R-L ids:
 * it states the reason and the way out; the ids live in docs/router.md and code comments.
 */
import { CONFIG_CACHE_SECONDS, SPEND_DAYS } from './tuning'

export const copy = {
  title: 'LLM router',
  loading: 'Loading the LLM router',
  howItWorks: 'How routing works',
  howTitle: 'How a call is routed',
  howSteps: [
    {
      title: 'Agent calls the router',
      detail: 'Every call from a routed agent or coding harness.',
    },
    {
      title: 'A config is chosen',
      detail: 'The agent’s attached config, else your default, else none.',
    },
    {
      title: 'A model is picked',
      detail: 'An override or a pin wins; otherwise a tier per request.',
    },
    { title: 'The provider is called', detail: 'With your saved key, or the platform key.' },
    { title: 'Fallbacks if it fails', detail: 'Each fallback model is tried in order.' },
  ],
  howClose: 'Hide how routing works',
  howShowDefaults: 'Show them',
  howCounts: (onDefault: string, total: string, name?: string) =>
    `${onDefault} of your ${total} agents use your default${name ? `, ${name}` : ''}.`,
  configuredNote:
    'Configured routing. Calls in flight may use the previous routing for up to an hour.',
  anchors: { agents: 'Agents', configs: 'Configs', budgets: 'Budgets', providers: 'Providers' },
  anchorsLabel: 'Sections',

  // Summary strip
  summaryLabel: 'Routing summary',
  atLeast: (n: number) => `at least ${n}`,
  summaryAgents: (n: string) => `${n} agents`,
  summaryDefault: (n: string, detail: string | null) =>
    `${n} on your default${detail ? ` (${detail})` : ''}`,
  summaryAttached: (n: string) => `${n} attached`,
  defaultDetail: (provider: string, yourKey: boolean) =>
    `${provider}, ${yourKey ? 'your key' : 'platform key'}`,
  filterNames: { attached: 'Attached', default: 'Your default', none: 'No config' },
  summaryNone: (n: string) => `${n} no config (platform key)`,
  kpiAgents: 'Your agents',
  kpiAgentsNote: 'Show all',
  kpiNoDefault: 'No default config',
  kpiAttachedNote: 'A config of their own',
  kpiNoneNote: 'Platform key',
  filteredBy: (what: string) => `Showing agents: ${what}`,
  clearFilter: 'Show all',
  foldedTitle: (n: string) => `${n} agents on your default`,
  foldedTitleMore: (n: string) => `${n} more on your default`,
  foldedDetail: (config: string, key: string) => `${config} · ${key}`,
  foldedShow: (n: string) => `Show all ${n}`,
  foldedHide: 'Hide',
  foldedSpend: (money: string, calls: string) => `${money} · ${calls} calls in 30 days`,
  searchAgents: 'Search agents',
  searchNone: (q: string) => `No agents match “${q}”`,
  searchNoneText: 'Try another name.',

  // Your agents
  agentsTitle: 'Your agents',
  colAgent: 'Agent',
  colSource: 'Source',
  colRouting: 'Routing',
  colKey: 'Key',
  colSpend: `Spend (${SPEND_DAYS} d, router)`,
  spendTip: `Metered by the router for the last ${SPEND_DAYS} days, calls billed to you. Calls billed to someone else don’t show here.`,
  colActions: 'Actions',
  changeRouting: 'Change routing',
  codingHarness: 'Coding harness',
  readingRouting: 'Reading routing…',
  couldntRead: 'Couldn’t read routing',
  retry: 'Retry',
  noAgents: 'You don’t own any agents yet',
  noAgentsText: 'Other users’ agents show their routing on their agent page.',
  toAgents: 'Go to Agents',
  noneInFilter: 'No agents match this filter',
  noneInFilterText: 'None of your agents has this kind of routing.',
  updatedMarker: (at: string, by: string) => `Updated ${at} · applies by about ${by}`,
  spendValue: (money: string, calls: string) => `${money} · ${calls} calls`,
  spendNone: 'No routed calls',
  spendFailed: 'Spend unavailable',
  unpricedMark: '*',
  unpricedNote: '* includes calls with no price (counted as $0)',
  partialNote: 'This list may be partial.',
  droppedNote: (n: string) => `${n} calls from deleted or other agents not shown.`,

  // Sources and badges
  source: {
    attached: 'Attached',
    default: 'Your default',
    ownerDefault: 'Owner’s default',
    none: 'No config',
  },
  defaultBadge: 'Default',
  customBadge: 'Custom',
  yourKey: (name: string) => `Your key · ${name}`,
  platformKey: 'Platform key',

  // Routing sentence (plan §4.7)
  overridden: (model: string) => `Overridden to ${model} (agent) · tiers and fallbacks off`,
  pinnedConfig: (model: string) => `Pinned to ${model} (config) · tiers and fallbacks off`,
  tiered: (models: string, fallbacks: string) => `Tiered: ${models} · ${fallbacks}`,
  tieredShort: (n: number) => `Tiered · ${n} models`,
  single: (provider: string, model: string, fallbacks: string) =>
    `${provider} · ${model} · ${fallbacks}`,
  noConfig: 'No config: the request’s model, platform key',
  fallsBack: (n: number) =>
    n === 0 ? 'no fallbacks' : n === 1 ? 'falls back to 1 model' : `falls back to ${n} models`,

  // Your configs
  configsTitle: 'Your configs',
  newConfig: 'New config',
  setADefault: 'Set a default',
  noConfigs: 'No configs yet',
  noConfigsText:
    'Until you add one, every agent uses the platform key and the model each request names.',
  createFirst: 'Create your first config',
  usedBy: (n: string) => `Used by ${n}`,
  configActions: (name: string) => `Actions for ${name}`,
  edit: 'Edit',
  setDefault: 'Set as default',
  removeDefault: 'Remove default',
  duplicate: 'Duplicate',
  delete: 'Delete',
  cliEquivalent: 'CLI equivalent',
  cliTiered: 'Tier models can’t be set from the CLI yet.',
  cliNoModel: 'This config has no model, so the CLI can’t create it yet.',
  copyCli: 'Copy CLI command',

  // Providers
  providersTitle: 'Providers',
  colProvider: 'Provider',
  colModels: 'Models',
  colPrice: 'In / out per 1M',
  noPrice: 'no price',
  noModels: 'No models synced',
  notRoutable: (p: string) =>
    `The router can’t call ${p}: it isn’t built in or a registered custom provider.`,
  registryTitle: 'Models the router picks per tier',
  registryWayOut: 'Superusers change these with nasiko model-registry set.',
  registryEmpty: 'No tier models set',
  tierLabels: ['Advanced reasoning', 'Balanced', 'Fast responses'] as const,
  catalogFailed: 'Couldn’t load the provider catalog',
  customProviders: 'Custom providers',
  noCustom: 'No custom providers',
  addCustom: 'Add custom provider',
  sync: {
    never: 'Never synced',
    syncing: 'Syncing…',
    synced: (when: string) => `Synced ${when}`,
    failed: (err: string) => `Sync failed: ${err}`,
  },
  syncNow: 'Sync models',
  syncDone: (name: string, n: number) => `Synced ${name}: ${n} models.`,
  keySaved: 'Key saved',

  // Config editor
  editorNew: 'New config',
  editorDescription: 'A provider, model and key your agents can share.',
  editorEdit: (name: string) => `Edit ${name}`,
  editorDuplicate: (name: string) => `Duplicate of ${name}`,
  fieldName: 'Name',
  fieldProvider: 'Provider',
  fieldModel: 'Model',
  modelHint: 'Required unless you set a tier model; with tiers it is the fallback model.',
  fieldKey: 'Key',
  keyUseSaved: 'Use a saved key',
  keyAdd: 'Add a key',
  keyPlatform: 'Platform key',
  noSavedKeys: 'No saved keys yet',
  secretsFailed: 'Couldn’t load your saved keys. You can still add a key or use the platform key.',
  secretName: 'Secret name',
  secretNameHint: 'Uppercase letters, digits and _ only.',
  keyValue: 'API key',
  keyReplaces: (name: string) =>
    `Replaces the saved key ${name} for every config and agent that uses it.`,
  keyContainers: 'Saved keys are also available to all your agents’ containers.',
  tierSection: 'Tier models (optional)',
  fallbacksSection: 'Fallbacks',
  addFallback: 'Add fallback',
  fallbackPlaceholder: 'provider/model, or a model on the same provider',
  moveUp: (e: string) => `Move ${e} up`,
  moveDown: (e: string) => `Move ${e} down`,
  removeFallback: (e: string) => `Remove ${e}`,
  movedTo: (e: string, pos: number) => `${e} moved to position ${pos}`,
  platformKeyFallback: (provider: string) =>
    `uses the platform key, if the platform has one for ${provider}`,
  notInCatalog: 'Not in the catalog',
  advanced: 'Advanced',
  temperature: 'Temperature',
  maxTokens: 'Max tokens',
  pinModel: 'Pin model',
  pinModelHint: 'A pinned model turns tier routing and fallbacks off.',
  pinModelRequired: 'Choose the model to pin.',
  cantClear:
    'OpenRuntime can’t clear this field yet. Duplicate without this field, or use the CLI.',
  duplicateWithout: 'Duplicate without this field',
  openrouterHidden: 'openrouter isn’t served here: calls will fail',
  missingKey: (name: string) => `Saved key ${name} not found: add it again`,
  providerGone: 'Provider no longer registered',
  useAsDefault: 'Use as my default',
  affects: (n: string) => `Affects ${n} of your agents.`,
  affectsDeleteDefault: (n: string) =>
    `Affects ${n} of your agents: they’ll use no config (the platform key and the request’s model).`,
  timing: `Changes apply normally within ${CONFIG_CACHE_SECONDS} seconds; ongoing conversations may keep their current model for up to an hour.`,
  save: 'Save',
  saving: 'Saving…',
  cancel: 'Cancel',
  done: 'Done',
  changedElsewhere: 'Changed elsewhere.',
  reload: 'Reload',
  loadingChoices: 'Loading…',
  notUsedYet: 'Not used by any agent yet.',
  attachAction: 'Attach to an agent',
  duplicateSaved: (n: string) => `Used by 0. The original is used by ${n} agents.`,
  keyMaybeSaved: 'The key may have been saved; the config wasn’t.',
  saved: (name: string) => `Saved ${name}.`,
  required: 'Required.',

  // Delete
  deleteTitle: (name: string) => `Delete ${name}?`,
  deleteBody: 'This can’t be undone here.',
  deleteInUse: (n: string) =>
    `This config is attached to ${n} agents. Change their routing first, then delete it.`,
  deleted: (name: string) => `Deleted ${name}.`,

  // Agent routing sheet
  routingTitle: (name: string) => `Change routing · ${name}`,
  routeWith: 'Route this agent with',
  useMyDefault: 'Use my default',
  useOwnersDefault: 'Use the owner’s default',
  useAConfig: 'Use a config',
  chooseConfig: 'Choose a config',
  overrideSection: 'Override',
  overrideModel: 'Override model',
  overridePlaceholder: 'Model to use for every call',
  removeOverride: 'Remove override',
  overrideWarning: 'Switching config removes this agent’s override.',
  keepOverride: 'Keep the override (re-added after the switch)',
  keepNotOffered: (model: string, provider: string) => `${model} isn’t offered by ${provider}`,
  keepAnyProvider: 'Applies to the provider each request names.',
  cantSeeOwnerConfigs: 'You can’t see this owner’s configs.',
  requestFormat: 'Request format',
  requestFormatWayOut: (agent: string) =>
    `Change with nasiko llm-config attach ${agent} <config> --inbound-format <format>.`,
  checkHint: (by: string) =>
    `To check, start a new conversation after ${by}: ongoing ones may keep the old model.`,
  cantConfirm: 'This page can’t confirm routed calls yet.',
  seeSessions: 'See its sessions',
  savedPlan: (name: string) => `Routing saved for ${name}.`,
  partialOverride: (model: string) =>
    `Config attached. The override wasn’t restored: ${model} is no longer pinned.`,
  partialOverrideDefault: (model: string) =>
    `Now on the default. The override wasn’t restored: ${model} is no longer pinned.`,
  pinAgain: 'Pin again',
  midwayFailed: (saved: string) => `Only part of the change was saved: ${saved}.`,
  stepAttach: 'the config was attached',
  stepDetach: 'the agent now uses the default',
  stepPin: 'the override was set',
  stepUnpin: 'the override was removed',
  nothingSaved: 'Nothing was saved.',
  cardTitle: 'LLM routing',
  cardOpenRouter: 'Open LLM router',
  labelSource: 'Source',
  labelProvider: 'Provider',
  labelModel: 'Model',
  labelKey: 'Key',
  labelFallbacks: 'Fallbacks',
  labelOverride: 'Override',
  none: 'Not set',

  // Budgets (R2, plan §5.1; proposed R-L10 contract, mocked)
  budgetsTitle: 'Budgets',
  budgetsSubtitle: (reset: string) =>
    `Router-metered spend this UTC month (token_usage). Covers routed calls only · resets ${reset}`,
  newBudget: 'New budget',
  noBudgets: 'No budgets yet',
  noBudgetsText:
    'A budget alerts you as spend crosses its marks, and can stop an agent’s calls at 100%.',
  createFirstBudget: 'Create a budget',
  budgetsFailed: 'Couldn’t load budgets',
  budgetsMissing: 'Budgets need a newer OpenRuntime server',
  budgetsMissingBody:
    'This section uses the proposed /api/budgets endpoints, which this server doesn’t have yet. Set VITE_NASIKO_MOCK=router,agents,providers to preview it with mock data.',
  unpriced: (n: string) => `${n} calls with no price count as $0`,
  stopKeeps100: 'Stop calls always alerts at 100%.',
  budgetChanged:
    'This budget changed elsewhere. Close the sheet and open it again to see the latest.',
  budgetStatusFailed: 'Couldn’t read this month’s spend for these budgets.',
  colScope: 'Scope',
  colUsedOfLimit: 'Used of limit',
  usedOf: (used: string, limit: string) => `${used} of ${limit}`,
  colForecast: 'Forecast',
  colState: 'State',
  colAt100: 'At 100%',
  budgetOwner: 'You',
  budgetOwnerHint: 'All calls billed to you',
  budgetOwnerOption: 'You (all calls billed to you)',
  budgetUnknownAgent: (id: string) => `Agent ${id.slice(0, 8)}… (not listed)`,
  budgetOk: 'OK',
  budgetWarning: (pct: number) => `Warning · ${pct}%`,
  budgetExceeded: 'Exceeded',
  forecastBand: (low: string, high: string) => (low === high ? high : `${low} – ${high}`),
  forecastTooEarly: 'Too early',
  forecastNoSpend: 'No spend yet',
  forecastStopped: 'Stopped at the limit',
  forecastNote:
    'Forecast: a month-end range from this month’s daily spend (median and mean daily rates), from day 3.',
  forecastOver: 'over the limit',
  actionAlert: 'Alert only',
  actionStop: 'Stop calls',
  stoppedUntil: (date: string) => `Calls get an error until ${date}`,
  raiseLimit: 'Raise limit',
  switchToAlert: 'Switch to Alert only',
  switchedToAlert: (name: string | null) =>
    `${name ? `${name} is` : 'Your budget is'} on Alert only. Calls resume within about a minute.`,
  alertsTitle: 'Alerts',
  alertsSubtitle: 'In-app, one per budget per mark per month. Email and webhooks are server work.',
  noAlerts: 'No alerts this month or last',
  alertCrossed: (label: string, pct: number, amount: string, stopped: boolean) =>
    `${label} crossed ${pct}% (${amount})${stopped ? ' · calls stopped' : ''}`,
  viewBudget: 'View budget',
  alertOwner: 'Your budget',

  // Budget sheet
  budgetNew: 'New budget',
  budgetEdit: (name: string | null) => `Budget · ${name ?? 'You (calls billed to you)'}`,
  budgetDescription:
    'A monthly limit on router-metered spend, with alerts as it crosses each mark.',
  budgetStatusLine: (used: string, limit: string, reset: string) =>
    `${used} used of ${limit} this month · resets ${reset} · router-metered`,
  budgetScope: 'Applies to',
  budgetScopeAgentHint: 'An agent budget counts every call to that agent, whoever is billed.',
  budgetScopeOwnerHint:
    'Your budget counts every routed call billed to you, including your chats with other people’s agents.',
  budgetNoScopes: 'Every agent you own already has a budget, and so do you.',
  monthlyLimit: 'Monthly limit (USD)',
  limitPositive: 'Enter an amount above $0.',
  alertAt: 'Alert at',
  alertAtHint: 'One in-app alert each time spend crosses a mark.',
  addThreshold: 'Add threshold',
  thresholdPlaceholder: 'e.g. 90',
  removeThreshold: (pct: number) => `Remove ${pct}%`,
  thresholdsRequired: 'Keep at least one mark.',
  thresholdRange: 'Use whole percents from 1 to 100.',
  thresholdDuplicate: 'That mark is already set.',
  at100: 'At 100%',
  alertOnlyHint: 'You get an alert; calls continue.',
  stopHint: 'The router refuses the calls this budget counts until the month resets.',
  stopConsequenceAgent: (agent: string, date: string) =>
    `Calls from ${agent} get an error until ${date}. Its callers see the agent’s normal error.`,
  stopConsequenceOwner: (date: string) =>
    `Every routed call billed to you gets an error until ${date}, including your chats with other people’s agents.`,
  budgetTiming: 'Limit changes apply within about a minute.',
  deleteBudget: 'Remove budget',
  deleteBudgetTitle: (name: string | null) =>
    name ? `Remove the budget for ${name}?` : 'Remove your budget?',
  deleteBudgetBody: 'Alerts stop and, if calls were stopped, they resume.',
  budgetSaved: (name: string | null) =>
    name ? `Budget saved for ${name}.` : 'Your budget is saved.',
  budgetDeleted: (name: string | null) =>
    name ? `Budget removed for ${name}.` : 'Your budget is removed.',

  // Custom provider sheet
  cpNew: 'Add custom provider',
  cpDescription: 'An endpoint the router can call, for every user’s configs.',
  cpEdit: (name: string) => `Edit ${name}`,
  cpName: 'Name',
  cpKind: 'Endpoint type',
  cpKinds: {
    openai: 'OpenAI-compatible',
    'azure-openai': 'Azure OpenAI',
    'bedrock-converse': 'AWS Bedrock',
  },
  cpKindHint: {
    openai: 'Speaks the OpenAI chat completions format.',
    'azure-openai':
      'An Azure OpenAI resource. OpenRuntime adds the deployment path and api-version.',
    'bedrock-converse': 'Bedrock Runtime’s Converse API, with a Bedrock API key.',
  },
  cpKindLocked: 'The endpoint type can’t change after registering. Add a new provider instead.',
  cpBaseUrl: 'Base URL',
  cpBaseUrlHint: {
    openai: 'The part before /chat/completions.',
    'azure-openai': 'The resource host only, e.g. https://<resource>.openai.azure.com.',
    'bedrock-converse': 'The region’s Bedrock Runtime endpoint.',
  },
  cpApiVersion: 'API version',
  cpBaseUrlBad: 'Use an http:// or https:// URL.',
  cpKey: 'API key',
  cpKeyKeep: 'Leave empty to keep the saved key.',
  cpKeyNewHost: 'New host: enter the key again. The saved key isn’t sent to a different host.',
  cpDefaultModel: 'Default model',
  cpSavedNoModel: (name: string) =>
    `Saved ${name}, but its default model wasn’t set. Edit the provider to set it.`,
  cpSync: 'Sync the model catalog',
  cpTest: 'Test',
  cpTesting: 'Testing…',
  cpTestNeedsKey: 'Enter the key to test.',
  cpTestOk: (n: number) => `Chat ok · ${n} models found`,
  cpTestModels: (n: number) => `${n} models found (chat not tested: no default model)`,
  // The server lists every user's configs on this provider (custom_providers.rs delete), not only the viewer's.
  cpDeleteRefs: (names: string) =>
    `Still used by: ${names}. Some may belong to other users; their owners must repoint them first.`,

  // Errors (errors.ts builds the entries)
  errUnmapped: (text: string, status: number) => `OpenRuntime said: ${text} (HTTP ${status})`,
  errDown: 'OpenRuntime isn’t answering.',
  errDownFix: 'Check that nasiko-server is running, then retry.',
} as const

/** Retired forms a copy test bans from this page (plan §2). */
export const RETIRED = [
  'effective routing',
  'will use the platform key',
  'Pinned to <model> (agent override)',
  'Ask Orchestrator',
] as const
