[package]
name = "nasiko-secrets"
edition.workspace = true
version.workspace = true

[dependencies]
aes-gcm = "0.10"
base64 = { workspace = true }
thiserror = { workspace = true }
hkdf = { workspace = true }
sha2 = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
